version: '3'

networks:
  osiris-network:
    driver: bridge

services:

  front-loadbalance:
    image: osiris/front-loadbalance
    container_name: osiris-front-end-loadbalance
    ports:
      - "85:85"
    networks:
      - osiris-network
    depends_on:
      - react

  back-loadbalance:
    image: osiris/back-loadbalance
    container_name: osiris-back-end-loadbalance
    ports:
      - "90:90"
    networks:
      - osiris-network
    depends_on:
      - springboot

  react:
    image: osiris/front-end
    container_name: osiris-front-end1
    ports:
      - "3000"
    networks:
      - osiris-network
    depends_on:
      - back-loadbalance

  springboot:
    image: osiris/springboot-api
    container_name: osiris-api1
    ports:
      - "8080"
    networks:
      - osiris-network
