version: '3'

networks:
  osiris-network:
    driver: bridge

services:
  react1:
    build:
      dockerfile: ./docker/react.dockerfile
      context: .
    image: osiris/front-end
    container_name: osiris-front-end
    ports:
      - "3000"
    networks:
      - osiris-network
    depends_on:
      - springboot1
      - springboot2

  springboot1:
    build:
      dockerfile: ./docker/springboot.dockerfile
      context: .
    image: osiris/springboot-api
    container_name: osiris-api
    ports:
      - "8080"
    networks:
      - osiris-network
  
  react2:
    build:
      dockerfile: ./docker/react.dockerfile
      context: .
    image: osiris/front-end
    container_name: osiris-front-end
    ports:
      - "3001"
    networks:
      - osiris-network
    depends_on:
      - springboot1
      - springboot2

  springboot2:
    build:
      dockerfile: ./docker/springboot.dockerfile
      context: .
    image: osiris/springboot-api
    container_name: osiris-api
    ports:
      - "8081"
    networks:
      - osiris-network