version: '3'

networks:
  osiris-network:
    driver: bridge

services:

  front-loadbalance:
    image: osiris/front-loadbalance
    ports:
      - "80:85" 
    networks:
      - osiris-network
    depends_on:
      - react

  back-loadbalance:
    image: osiris/back-loadbalance
    networks:
      - osiris-network
    depends_on:
      - springboot

  react:
    image: osiris/frontend
    networks:
      - osiris-network
    depends_on:
      - back-loadbalance

  springboot:
    image: osiris/backend
    networks:
      - osiris-network
