version: '3'

networks:
  osiris-network:
    driver: bridge

services:

  front-loadbalance:
    image: osiris/front-loadbalance
    ports:
      - "80:80"
    networks:
      - osiris-network
    depends_on:
      - react

  back-loadbalance:
    image: osiris/back-loadbalance
    ports:
      - "80"
    networks:
      - osiris-network
    depends_on:
      - springboot

  react:
    image: osiris/frontend
    ports:
      - "3000"
    networks:
      - osiris-network
    depends_on:
      - back-loadbalance

  springboot:
    image: osiris/backend
    ports:
      - "8080"
    networks:
      - osiris-network
