-- MySQL Script generated by MySQL Workbench
-- 03/19/21 19:08:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osiris` DEFAULT CHARACTER SET utf8 ;
USE `osiris` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ecommerce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`Ecommerce` ;

CREATE TABLE IF NOT EXISTS `osiris`.`Ecommerce` (
  `idEcommerce` INT NOT NULL AUTO_INCREMENT,
  `cnpj` CHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEcommerce`)
  );

insert into ecommerce values
(null, "01234567891234", "ficticio");


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `osiris`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `fkEcommerce` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Ecommerce`
  FOREIGN KEY (`fkEcommerce`)
  REFERENCES `osiris`.`Ecommerce` (`idEcommerce`)
);

insert into usuario values
(null, "zezinho", "12345", 1);


-- -----------------------------------------------------
-- Table `mydb`.`cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`cupom` ;

CREATE TABLE IF NOT EXISTS `osiris`.`cupom` (
  `idCupom` INT NOT NULL AUTO_INCREMENT,
  `nomeCupom` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(3,2) NOT NULL,
  `dataEmitido` DATETIME NOT NULL,
  `dataValidado` DATETIME NOT NULL,
  `cupomEcommerce` BOOLEAN NOT NULL,
  `idConsumidorEcommerce` INT NOT NULL,
  `usado` BOOLEAN NOT NULL,
  PRIMARY KEY (`idCupom`)
);

insert into cupom values
(null, "", 0.0, "2021-03-31", "2021-03-26", true, 505, false),
(null, "OSIRIS10", 0.1, "2021-03-31", "2021-03-26", false, 203, true),
(null, "OSIRIS20", 0.2, "2021-04-10", "2021-04-05", true, 505, false),
(null, "OSIRIS50", 0.5, "2021-04-15", "2021-04-10", false, 203, true);


-- -----------------------------------------------------
-- Table `mydb`.`dominioStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`dominioStatus` ;

CREATE TABLE IF NOT EXISTS `osiris`.`dominioStatus` (
  `idDominioStatus` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDominioStatus`)
);

insert into dominioStatus values
(null, "Cancelada"),
(null, "Finalizada");


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`evento` ;

CREATE TABLE IF NOT EXISTS `osiris`.`evento` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `idConsumidorEcommerce` INT NOT NULL,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `nomeCategoria` VARCHAR(45) NOT NULL,
  `dataCompra` DATETIME NOT NULL,
  `cupom` VARCHAR(45) NULL,
  `fkEcommerce` INT NOT NULL,
  `fkCupom` INT NOT NULL,
  `fkStatus` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  CONSTRAINT `fk_compra_Ecommerce`
    FOREIGN KEY (`fkEcommerce`)
    REFERENCES `osiris`.`Ecommerce` (`idEcommerce`),
  CONSTRAINT `fk_compra_cupom`
    FOREIGN KEY (`fkCupom`)
    REFERENCES `osiris`.`cupom` (`idCupom`),
  CONSTRAINT `fk_evento_dominioStatus`
    FOREIGN KEY (`fkStatus`)
    REFERENCES `osiris`.`dominioStatus` (`idDominioStatus`)
);

insert into evento values
(null, 505, "Calça jeans", 70.89, "Roupas", "2021-03-26", "", 1, 1, 1),
(null, 505, "Camiseta", 70.89, "Roupas", "2021-03-26", "OSIRIS20", 1, 2, 2),
(null, 505, "Mouse gamer", 70.89, "Periféricos", "2021-03-26", "CASCA10", 1, 1, 2),
(null, 203, "Teclado USB", 70.89, "Periféricos", "2021-03-26", "CASCA10", 1, 1, 2),
(null, 203, "Teclado USB", 70.89, "Periféricos", "2021-03-26", "CASCA10", 1, 1, 2);


-- -----------------------------------------------------
-- Table `mydb`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`acesso` ;

CREATE TABLE IF NOT EXISTS `osiris`.`acesso` (
  `idAcesso` INT NOT NULL AUTO_INCREMENT,
  `idConsumidorEcommerce` INT NOT NULL,
  `inicioAcesso` DATETIME NOT NULL,
  `fimAcesso` DATETIME NOT NULL,
  PRIMARY KEY (`idAcesso`)
);

insert into acesso values
(null, 505, "2021-03-26", "2021-03-27"),
(null, 203, "2021-03-27", "2021-03-28");
  
-- -----------------------------------------------------
-- Table `mydb`.`cluster`
-- -----------------------------------------------------
  
DROP TABLE IF EXISTS `osiris`.`cluster` ;

CREATE TABLE IF NOT EXISTS `osiris`.`cluster` (
  `idCluster` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `nomeCluster` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCluster`)
); 

-- -----------------------------------------------------
-- Table `mydb`.`meta`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `osiris`.`meta` ;

CREATE TABLE IF NOT EXISTS `osiris`.`meta` (
  `idMeta` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `fkEcommerce` INT NOT NULL,
  PRIMARY KEY (`idMeta`),
  CONSTRAINT `fk_meta_ecommerce`
  FOREIGN KEY (`fkEcommerce`)
  REFERENCES `osiris`.`ecommerce` (`idEcommerce`)
); 
  
  insert into meta values
  (null, "2021-04-01", "2021-04-30", 100.00, 1);

select * from acesso;

select * from evento where id_consumidor_ecommerce = 203 group by nome_produto;

select count(id_acessos) as quantidade from acessos where inicio_acesso between current_date()-7 and current_date();
select count(id_compra) as quantidade from evento;
select count(id_acessos) as quantidade from acessos;
select nome_categoria, count(id_compra) as quantidade from evento group by nome_categoria order by quantidade desc limit 5;

select count(id_compra) as quantidade from evento where id_consumidor_ecommerce = 203;

