-- MySQL Script generated by MySQL Workbench
-- 03/19/21 19:08:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osiris` DEFAULT CHARACTER SET utf8 ;
USE `osiris` ;

-- -----------------------------------------------------
-- Table `mydb`.`ecommerce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`ecommerce` ;

CREATE TABLE IF NOT EXISTS `osiris`.`ecommerce` (
  `id_ecommerce` INT NOT NULL AUTO_INCREMENT,
  `cnpj` CHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ecommerce`)
  );

insert into ecommerce values
(null, "01234567891234", "ficticio");


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`usuario` ;

CREATE TABLE IF NOT EXISTS `osiris`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `fk_ecommerce` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_ecommerce`
  FOREIGN KEY (`fk_ecommerce`)
  REFERENCES `osiris`.`ecommerce` (`id_ecommerce`)
);

insert into usuario values
(null, "zezinho", "12345", 1);


-- -----------------------------------------------------
-- Table `mydb`.`cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`cupom` ;

CREATE TABLE IF NOT EXISTS `osiris`.`cupom` (
  `id_cupom` INT NOT NULL AUTO_INCREMENT,
  `nome_cupom` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(3,2) NOT NULL,
  `data_emitido` DATETIME NOT NULL,
  `data_validado` DATETIME NOT NULL,
  `cupom_ecommerce` BOOLEAN NOT NULL,
  `id_consumidor_ecommerce` INT NOT NULL,
  `usado` BOOLEAN NOT NULL,
  PRIMARY KEY (`id_cupom`)
);

insert into cupom values
(null, "", 0.0, "2021-03-31", "2021-03-26", true, 505, false),
(null, "OSIRIS10", 0.1, "2021-03-31", "2021-03-26", false, 203, true),
(null, "OSIRIS20", 0.2, "2021-04-10", "2021-04-05", true, 505, false),
(null, "OSIRIS50", 0.5, "2021-04-15", "2021-04-10", false, 203, true);


-- -----------------------------------------------------
-- Table `mydb`.`dominioStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`dominio_status` ;

CREATE TABLE IF NOT EXISTS `osiris`.`dominio_status` (
  `id_dominio_status` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dominio_status`)
);

insert into dominio_status values
(null, "Cancelada"),
(null, "Finalizada");


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`evento` ;

CREATE TABLE IF NOT EXISTS `osiris`.`evento` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `id_consumidor_ecommerce` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `cupom` VARCHAR(45) NULL,
  `fk_ecommerce` INT NOT NULL,
  `fk_cupom` INT NOT NULL,
  `fk_status` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_compra_ecommerce`
    FOREIGN KEY (`fk_ecommerce`)
    REFERENCES `osiris`.`ecommerce` (`id_ecommerce`),
  CONSTRAINT `fk_compra_cupom`
    FOREIGN KEY (`fk_cupom`)
    REFERENCES `osiris`.`cupom` (`id_cupom`),
  CONSTRAINT `fk_evento_dominio_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `osiris`.`dominio_status` (`id_dominio_status`)
);

insert into evento values
(null, 505, "Calça jeans", 70.89, "Roupas", "2021-03-26", "", 1, 1, 1),
(null, 505, "Camiseta", 70.89, "Roupas", "2021-03-26", "OSIRIS20", 1, 2, 2),
(null, 505, "Mouse gamer", 70.89, "Periféricos", "2021-03-26", "CASCA10", 1, 1, 2),
(null, 203, "Teclado USB", 70.89, "Periféricos", "2021-03-26", "CASCA10", 1, 1, 2),
(null, 203, "Teclado USB", 70.89, "Periféricos", "2021-03-26", "CASCA10", 1, 1, 2);


-- -----------------------------------------------------
-- Table `mydb`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `osiris`.`acesso` ;

CREATE TABLE IF NOT EXISTS `osiris`.`acesso` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `id_consumidor_ecommerce` INT NOT NULL,
  `inicio_acesso` DATETIME NOT NULL,
  `fim_acesso` DATETIME NOT NULL,
  PRIMARY KEY (`id_acesso`)
);

insert into acesso values
(null, 505, "2021-03-26", "2021-03-27"),
(null, 203, "2021-03-27", "2021-03-28");
  
-- -----------------------------------------------------
-- Table `mydb`.`cluster`
-- -----------------------------------------------------
  
DROP TABLE IF EXISTS `osiris`.`cluster` ;

CREATE TABLE IF NOT EXISTS `osiris`.`cluster` (
  `id_cluster` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nome_cluster` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cluster`)
); 

-- -----------------------------------------------------
-- Table `mydb`.`meta`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `osiris`.`meta` ;

CREATE TABLE IF NOT EXISTS `osiris`.`meta` (
  `id_meta` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `fk_ecommerce` INT NOT NULL,
  PRIMARY KEY (`id_meta`),
  CONSTRAINT `fk_meta_ecommerce`
  FOREIGN KEY (`fk_ecommerce`)
  REFERENCES `osiris`.`ecommerce` (`id_ecommerce`)
); 
  
  insert into meta values
  (null, "2021-04-01", "2021-04-30", 100.00, 1);

select * from acesso;

select * from evento where id_consumidor_ecommerce = 203 group by nome_produto;

select count(id_acesso) as quantidade from acesso where inicio_acesso between current_date()-7 and current_date();
select count(id_compra) as quantidade from evento;
select count(id_acesso) as quantidade from acesso;
select nome_categoria, count(id_compra) as quantidade from evento group by nome_categoria order by quantidade desc limit 5;

select count(id_compra) as quantidade from evento where id_consumidor_ecommerce = 203;

