version: "3.3"
services:

  database:
    build:
      context: .
      dockerfile: processamento-db.Dockerfile
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=bandtec
      - MYSQL_DATABASE=processamento_db
    network_mode: host
  
  r-scripts:
    build:
      context: .
      dockerfile: run-scripts.Dockerfile
    container_name: scripts
    depends_on:
      - database
    restart: "no"
    network_mode: host
