version: '3'

networks:
  osiris-network:
    driver: bridge

services:

  server:
    image: ghcr.io/osiris-gp8/server:latest-ti
    ports:
      - 80:85
    networks:
      - osiris-network
    depends_on:
      - springboot

  springboot:
    image: ghcr.io/osiris-gp8/backend:latest-ti
    ports:
      - 8080:8080
    networks:
      - osiris-network