name: Esteira de desenvolvimento da Osiris
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Configurando versão do Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Configurando versão do Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build e Package da API Java
        working-directory: osiris-api/
        run: |
          mvn clean install
          mvn package

      - name: npm install
        working-directory: front-end-osiris/
        run: npm install

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: TI
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Subindo aplicação na EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.AWS_ADRESS }}
          USER: ${{ secrets.AWS_USER }}
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: https://docker.pkg.github.com

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -O StrictHostKeyChecking=no  -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/3CCO-2021-1-Grupo-08 &&
            git pull &&
            docker-compose up -d --build
          '
